-- MySQL Script generated by MySQL Workbench
-- Tue Mar 21 17:05:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simple_eshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema simple_eshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple_eshop` DEFAULT CHARACTER SET utf8 ;
USE `simple_eshop` ;

-- -----------------------------------------------------
-- Table `simple_eshop`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `Password` VARCHAR(255) NOT NULL,
  `Registration_date` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Item_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Item_category` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Brand` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Item_model`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Item_model` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Item_name` VARCHAR(255) NOT NULL,
  `Sold_since` DATETIME NOT NULL,
  `Comments` LONGTEXT NULL,
  `Description` LONGTEXT NULL,
  `Brand_id` INT UNSIGNED NOT NULL,
  `Category_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stuff_Category1_idx` (`Category_id` ASC),
  INDEX `fk_Stuff_Brand1_idx` (`Brand_id` ASC),
  CONSTRAINT `fk_Stuff_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `simple_eshop`.`Item_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stuff_Brand1`
    FOREIGN KEY (`Brand_id`)
    REFERENCES `simple_eshop`.`Brand` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Arrival_date` DATETIME NOT NULL DEFAULT NOW(),
  `Item_state` VARCHAR(255) NOT NULL DEFAULT 'New',
  `Price` DOUBLE UNSIGNED NOT NULL,
  `Varanty` VARCHAR(255) NOT NULL DEFAULT '2 Years',
  `Item_model_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_Stuff1_idx` (`Item_model_id` ASC),
  CONSTRAINT `fk_Stock_Stuff1`
    FOREIGN KEY (`Item_model_id`)
    REFERENCES `simple_eshop`.`Item_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Orders` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Item` VARCHAR(255) NOT NULL,
  `Order_date` VARCHAR(255) NOT NULL DEFAULT 'NOW()',
  `Status` VARCHAR(255) NOT NULL,
  `Users_id` INT UNSIGNED NOT NULL,
  `Stock_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Orders_Users_idx` (`Users_id` ASC),
  INDEX `fk_Orders_Stock1_idx` (`Stock_id` ASC),
  CONSTRAINT `fk_Orders_Users`
    FOREIGN KEY (`Users_id`)
    REFERENCES `simple_eshop`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Orders_Stock1`
    FOREIGN KEY (`Stock_id`)
    REFERENCES `simple_eshop`.`Stock` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Properties` (
  `Category_id` INT UNSIGNED NOT NULL,
  `Item_type_id` INT UNSIGNED NOT NULL,
  `GPU_performance` VARCHAR(255) NULL,
  `CPU_performance` VARCHAR(255) NULL,
  PRIMARY KEY (`Category_id`, `Item_type_id`),
  INDEX `fk_Category_has_Item_type_Item_type1_idx` (`Item_type_id` ASC),
  INDEX `fk_Category_has_Item_type_Category1_idx` (`Category_id` ASC),
  CONSTRAINT `fk_Category_has_Item_type_Category1`
    FOREIGN KEY (`Category_id`)
    REFERENCES `simple_eshop`.`Item_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Category_has_Item_type_Item_type1`
    FOREIGN KEY (`Item_type_id`)
    REFERENCES `simple_eshop`.`Item_model` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple_eshop`.`Item_subcategory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simple_eshop`.`Item_subcategory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Item_category_id` INT UNSIGNED NOT NULL,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Item_subcategory_Item_Category1_idx` (`Item_category_id` ASC),
  CONSTRAINT `fk_Item_subcategory_Item_Category1`
    FOREIGN KEY (`Item_category_id`)
    REFERENCES `simple_eshop`.`Item_category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
